### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by MartinMikita** [klokantech/osmnames-sphinxsearch#1]
Prepare docker image with:
- [x] sphinxsearch
- [x] reloader for DB (TSV) in /data/ - http://sphinxsearch.com/docs/current.html#xsvpipe
- [ ] python web server for search API - like http://nominatim.klokantech.com/?q=paris&format=json

**Comment by klokan** [comment]
BTW the early spec of the project now in README.md https://github.com/geometalab/osmnames

**Comment by klokan** [comment]
Docker hub configured for autobuild: https://hub.docker.com/r/klokantech/osmnames-sphinxsearch/

**Comment by MartinMikita** [comment]
@klokan Do we want one docker image with sphinx + nginx + web (flask python app), or as I have done for maprank, 2 separate docker images, using docker-compose.yml + klokantech/nginx?

**Comment by klokan** [comment]
Create monolith now (everything behind a single supervisord in one container) - start with https://github.com/klokan/iiifserver-build/tree/master/docker_monolith

Now it is only for development and testing. For production deployment at later point we may need microservice instead, but this could be done later.

**Comment by MartinMikita** [comment]
Sources to use:
https://github.com/geoadmin/service-sphinxsearch

Implement autocomplate JS in index.html:
https://github.com/klokantech/javascript/blob/master/src/nominatim.js
Usage: `new kt.Nominatim(input, url)`

**Comment by petrsloup** [comment]
@MartinMikita latest build of klokantech/javascript compiled at http://klokantech.github.io/javascript/kt.js
If needed, http://klokantech.github.io/styles/base.css can be used for styling the autocomplete results (`.ac-*` css classes).

**Comment by MartinMikita** [comment]
This javascript should be copied into repository, or linked from HTML to build URL?

**Comment by klokan** [comment]
Linked for now, if you don't need to compile the JS yourself.

**Comment by MartinMikita** [comment]
Docker image is prepared, now it contains script for indexing display_name, class, type, lat+lon, using my sample.tsv

Main page contains autocomplete JavaScript, which uses endpoint "/search" - this search through all indices.
Endpoint "/displayName" search only in `display_name` index (contains indices normal, morphology=metaphone and morphology=soundex)
Endpoint "/custom" contains form with select to index, in which it should search value.

What is next task?

**Comment by klokan** [comment]
Thanks @MartinMikita - we are waiting for Basic data (should be delivered by HSR students next week) - then we make next small steps on this project as well.

Thank you a lot for working on this!
