### ISSUE TITLE
Speedup of search

### ISSUE THREAD

**Issue by MartinMikita** [klokantech/osmnames-sphinxsearch#15]
The following changes were done for speedup of search:
- parameters for [mysql search](http://sphinxsearch.com/docs/current.html#sphinxql-select):
  - `retry_count = 2`, distributed retries count
  - `retry_delay = 500`, distributed retry delay, msec
  - `cutoff = 100`, max found matches threshold (now it shows Total results 100)
  - `max_matches = 200`, per-query max matches value, default 1000
  - `max_query_time = 10000`, max search time threshold, msec (10s)
- parameters for [searchd](http://sphinxsearch.com/docs/current.html#ref-searchd):
  - `read_timeout = 5`, network client request read timeout, in seconds, default 5 seconds
  - `client_timeout = 1`, maximum time to wait between requests (in seconds), default 5 minutes (300)
  - `read_buffer = 1M`, Per-keyword read buffer size, default is 256K. Increasing per-query RAM use, but possibly decreasing IO time
  - parameters for websearch.py (uwsgi):
  - `max-requests = 10000` (was 1000)
  - `workers = 6` (was 1)
  - `harakiri = 60` - number of seconds, after which process is killed (if not respond, timeout)

**Comment by MartinMikita** [comment]
Important note, `cutoff` parameter affects results: it will stop searching.

**Comment by klokan** [comment]
I guess this can be closed - once bug #32 is fixed @MartinMikita

**Comment by MartinMikita** [comment]
1. Indexer is using sorted data based on importance. If more rows are indexed, they are already sorted by importance in a result - we just adjust sorting based on query for first 2000 results.
2. Basically two phases are used for searching: "exact or prefix", and "infix, or soundex infix, or split".
   Second phase is executed only if no results are given from the first phase.

Each phase consists few modifiers and different index (exact and prefix are separated), and with different field_weights. Field weights are descending slowly but significantly enough to give expected results.

**Comment by klokan** [comment]
Multiple threads are not used on a single index - large index must be chunked for the number of threads. I see we use 6 threads.
http://stackoverflow.com/questions/11829607/sphinx-scalability
- Do we chunk the indexes?
- If we initially search only in one - it may speed up the search by the factor of threads, theoretically...

**Comment by MartinMikita** [comment]
The source file is now split into 4 chunks equally.

The size of index files in sum hasn't changed.
The speed of index operation has slightly increased, but search speed seems to be improved.
