### ISSUE TITLE
Cache results

### ISSUE THREAD

**Issue by MartinMikita** [klokantech/osmnames-sphinxsearch#17]
Data are static, no change is expected.

Sphinxsearch `searchd` has some internal cache for repeated queries, but we don't know how it is managed.

Idea:
- cache full results of requests, save it for 1 week from the last "visit"
- cache results for autocomplete is not long, it could be in some SQLiteDB with hash
- use memcache / varnish with correct settings

**Comment by MartinMikita** [comment]
@o1da what do you suggest? I think you have more experience with caching.

**Comment by klokan** [comment]
For now we will use only CDN caching

**Comment by klokan** [comment]
An aggressive cache on the CDN is configured now (up to one month on the edge servers).
After deployment of a new version of the software or update of the data we must manually flush it.
Caching friendly headers and responses may help a lot #28.

Redirects are not yet active - but are going to be turned on once we upgrade the existing clients.

Implementation of local cache probably later on - with a new ticket. Closing.

**Comment by petrsloup** [comment]
@klokan The caching does not work at the moment.

Because _"The Ignore Query String setting only applies to static file extensions."_ (see https://support.cloudflare.com/hc/en-us/articles/200168256-What-are-CloudFlare-s-caching-levels- and https://support.cloudflare.com/hc/en-us/articles/200172516-Which-file-extensions-does-CloudFlare-cache-for-static-content-)

**Comment by klokan** [comment]
I have contacted the support with relevant request:
https://support.cloudflare.com/hc/en-us/requests/1192193

**Comment by klokan** [comment]
A workaround is to add `.js` suffix to every submitted request, as this extension is on the list.

Then everything would run as we want. The `.json` suffix would be better, but I guess this is acceptable for us too.
The server can return the same result for both `/q/brno` and `/q/brno.js`, and we set the rules for redirecting away from CDN if `.js` suffix is missing.

@MartinMikita, @petrsloup could you please implement this on both server and client side and deploy new versions?

**Comment by MartinMikita** [comment]
Server is prepared. @petrsloup let me know, if I can deploy it or you need to make some change in this repository.

**Comment by klokan** [comment]
@petrsloup could you please adjust the client?

**Comment by petrsloup** [comment]
Deployed, caching seems to be working ok..
