### ISSUE TITLE
Empty records not empty in search results

### ISSUE THREAD

**Issue by klokan** [klokantech/osmnames-sphinxsearch#18]
In the results there are often empty records with `" "` written like:

```
"wikipedia": "\" \"",
```

Why is there this quoted space? Is it already in the input TSV?
If it is in the input TSV before indexing - we must report it to osmnames project...

**Comment by MartinMikita** [comment]
This is in the source TSV, there is more columns like this.

![image](https://cloud.githubusercontent.com/assets/2283182/17098044/9d228016-5260-11e6-8125-7936fc2b3680.png)

**Comment by MartinMikita** [comment]
Fixed in https://github.com/geometalab/OSMNames/issues/39
