### ISSUE TITLE
Specification of input TSV file

### ISSUE THREAD

**Issue by MartinMikita** [klokantech/osmnames-sphinxsearch#2]
Input TSV file is Tab Separated Values, without header line.
Sphinx definition: tsvpipe has tab character as hardcoded delimiter and has no quoting rules.
Each value is interpreted as string inside sphinxsearch, nevertheless of quotes. **Using tab character inside text values is not possible!**

We need specific column order from input TSV file, because this order is than used in sphinx configuration.

Columns:
- osm_id - **MUST BE UNIQUE INTEGER "DOCUMENT ID"** accross complete database
- display_name
- name (=utf-8)
- name_en
- name_de
- name_es
- name_fr
- name_ru
- name_zh
- class
- type
- north (=boundingbox)
- south
- east
- west
- lat
- lon
- scalerank - we have it
- place_rank - nominatim has it
- importance - exactly as in nominatim calculated
- country (=country code, ISO-3166 2-letter country code)
- street=< housenumber > < streetname >
- city=< city >
- county=< county >
- state=< state >
- country=< country >
- postalcode=< postalcode >

**Comment by klokan** [comment]
Related tickets: https://github.com/geometalab/OSMNames/issues/1 and https://github.com/geometalab/OSMNames/issues/3

**Comment by klokan** [comment]
The students from HSR @lukasmartinelli and @manuelroth will prepare a first basic export based on the possibilities of what we have now in OSM2VectorTiles database.

Once they provide the first export file we adjust our sphinx.conf to be aligned to what they supply - and we will use this for initial tests.

The final exact official definition of the OSMNames project is now discussed - and final decisions are to be made at later point.

**Comment by klokan** [comment]
It settled down - in the https://github.com/geometalab/OSMNames repo.
