### ISSUE TITLE
CORS AJAX instead of JSONP

### ISSUE THREAD

**Issue by klokan** [klokantech/osmnames-sphinxsearch#22]
To improve the speed of response from gazeteer via CDN caching across all our project we should in the autocomplete component use CORS AJAX queries instead of JSONP.

It seems osmnames.klokantech.com has `Access-Control-Allow-Origin:*`.

BTW I also suggest using the standard delay everywhere (was it 350ms?)

**Comment by klokan** [comment]
This modification should probably happen at https://github.com/klokantech/javascript

**Comment by petrsloup** [comment]
I think the CORS headers are not there now.
@MartinMikita Could you please add the `Access-Control-Allow-Origin: *` header? If it's easier, add it to all pages (we currenly have no sessions or anything so it should be safe).

**Comment by petrsloup** [comment]
Done and deployed

**Comment by petrsloup** [comment]
@MartinMikita When you have a chance, please deploy the https://github.com/klokantech/osmnames-sphinxsearch/commit/23a0845a955799b04ea772c1c0f7a39aa77f96e7 commit, so we can do AJAX requests from other domains.

**Comment by klokan** [comment]
@petrsloup - has this been deployed? Can this be deployed now?
