### ISSUE TITLE
Issue with "Náměstí Svobody" query

### ISSUE THREAD

**Issue by klokan** [klokantech/osmnames-sphinxsearch#23]
"Namesti Svobody Brno" will not find what we need.

Results for "nam svobody", "namesti svobody", "Náměstí Svobody" are strange as well.
Let's dig into reasons for this.

**Comment by klokan** [comment]
I guess the reason is that streets have mostly constant importance 0.1 - not influenced by the city/town/vilage where they are - so it is a problem of data.

In fact I have seen on "namesti svobody brno" even lower `importance": 0.075,`. It should be higher then the others.

It seems to be a bug in the data. Reported at https://github.com/geometalab/OSMNames/issues/46

**Comment by MartinMikita** [comment]
Query `Namesti Svobody Brno` is now working.

The street importance was fixed, should be released within OSMNames v2.0 data.

**Comment by MartinMikita** [comment]
This is fixed with v2.0.
