### ISSUE TITLE
Wrong country code filter does not error

### ISSUE THREAD

**Issue by klokan** [klokantech/osmnames-sphinxsearch#26]
Queries like: 
http://osmnames.klokantech.com/?q=Edin&format=json&country_code=uk&autocomplete=1
takes forever.

It should stop to search much sooner - as the correct country_code is "gb" - code "uk" does not exist. There can't be results...

Isn't there an implementation bug @MartinMikita ?

**Comment by MartinMikita** [comment]
There is no checking for filter values now.

There are 249 different country_code values in planet-1.1.

Simple SQL query for checking takes ~1,5 second `select count(*) from ind_name_prefix where country_code = 'uk';`

We may improve filtering by country_code - load values from DB into global variable (once per life of flask app) and check before accessing to the DB. (loading from DB  takes ~5 sec in the beginning of the flask app).

Same can be done for:
- `class`, 5 values, loading ~5 sec
- `osm_type`, 3 values

Column type contains 3 102 different values.

**Comment by klokan** [comment]
Heh!? This is a task for database / fulltext engine - not for application.
The application should not be doing similar hacks and preloading.

Are you sure it is not bug in the query or your usage of sphinxsearch?

I have seen this:
https://www.percona.com/blog/2013/01/15/sphinx-search-performance-optimization-attribute-based-filtering/

It explains that attributes are not indexed at all in SphinxSearch. We have to be very careful with them - as they cause a scan of the records. Often used attributes should be turned to fulltext indexed match.

**Comment by klokan** [comment]
OK. Will you include the startup initialisation with the selects doing the scan on the attributtes, please?

**Comment by MartinMikita** [comment]
Check for `country_code` and `class` is made using preload list of these attribute's values.

Loading is made also if timestamp of file has been changed and request had `if-modified-since` header.
