### ISSUE TITLE
JavaScript country_code filter

### ISSUE THREAD

**Issue by klokan** [klokantech/osmnames-sphinxsearch#27]
The JavaScript interface does not allow to set filters - where the most wanted one is probably country_code - but there are more...

We need this to demo the osmnames project to potential customers...

Maybe it could be implemented together with permalinks - after # in URL, so a query like:

http://osmnames.klokantech.com/#q=George%20IV&country_code=gb

would add `country_code` to JSON request - and preserve it in the URL?
And typed query would adjust whatever is after `q=`?

**Comment by petrsloup** [comment]
Implemented and deployed
