### ISSUE TITLE
Deploy to osmnames.klokantech.com

### ISSUE THREAD

**Issue by klokan** [klokantech/osmnames-sphinxsearch#3]
Let's deploy the first version to: http://osmnames.klokantech.com/.

Sample data with first line:
`name    class   type    lon     lat     west    south   east    north`
are available at https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/v1.2/osmnames/roads.tsv.gz

Downloaded on the selma server in /data/roads.tsv.gz

**Comment by MartinMikita** [comment]
Size:
- `roads.tsv.gz` - 3.8GB
- `roads.tsv` - 13GB,  99 321 598 lines
- corrected `roads.tsv` - 13GB, 97 282 720 lines
- index on name:
  - normal: 281MB indexed fields, 65MB word list (word IDs and pointers to indexed fields)
  - metaphone: 550MB indexed fields, 70MB word list
  - soundex: 552MB fields, 68MB word list
- index on class:
  - normal: 385MB indexed fields, 1.1KB word list
  - metaphone: 770MB fields, 1.3KB word list
  - soundex: 770MB fields, 1.4KB word list
- index on type:
  - normal: 382MB fields, 3.9KB word list
  - metaphone: 763MB fields, 4.9KB word list
  - soundex: 763MB fields, 5.0KB word list

Each index (3x3) contains same file size for attributes and string attributes data in two separate files: 4.1GB (.spa) and 2.0GB (.sps)

Total size used by index is 60GB.

Each index (3x3) took ~1200 seconds to process, in total ~2.8 hours.

**Comment by MartinMikita** [comment]
Local index on class and type is not working now, because of error message `preload: mmap() failed: Cannot allocate memory (length=4347321704 is over 2GB, impossible on some 32-bit systems); NOT SERVING`

**Comment by MartinMikita** [comment]
This has been now fixed with option [ondisk-attrs = 1](http://sphinxsearch.com/docs/current.html#conf-ondisk-attrs) - it doesn't load spa, sps and spm files into memory - it will be slower.
