### ISSUE TITLE
Production deploy is down now 

### ISSUE THREAD

**Issue by klokan** [klokantech/osmnames-sphinxsearch#30]
http://osmnames.klokantech.com/?autocomplete=1&count=1&format=json&q=Prague

`Can't connect to MySQL server on '127.0.0.1`

The OSMNames is in use at maps.klokantech.com - launched on FOSS4G.
Once it will be more stable - we start to use it everywhere.

**Comment by MartinMikita** [comment]
Sorry, I was trying to reindex data and there were few errors.
The service is now working, I am going to test performance on a local server.
