### ISSUE TITLE
Access-Control-Allow-Origin not set anymore

### ISSUE THREAD

**Issue by klokan** [klokantech/osmnames-sphinxsearch#35]
While trying http://osmnames.klokantech.com/ - I am now getting an error: 

```
XMLHttpRequest cannot load https://osmnames.klokantech.com/q/bern?key=dgb7TgC5zR0YpsAqbEgb. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://osmnames.klokantech.com' is therefore not allowed access.
```

Have you removed the CORS headers from the server?

**Comment by MartinMikita** [comment]
I have only added "alias URL", but Flask was redirecting from `/q/<query>` to `/q/<query>.js` - the latest unique route is canonical.

It is fixed now.
But results are not caching now? Because I don't see CF headers in response.

**Comment by klokan** [comment]
Thanks.

On request like:
https://osmnames.klokantech.com/q/brno.js?key=dgb7TgC5zR0YpsAqbEgb
it returns me header
`cf-cache-status:HIT`
