### ISSUE TITLE
Specification of output JSON

### ISSUE THREAD

**Issue by MartinMikita** [klokantech/osmnames-sphinxsearch#4]
We need to specify output JSON format, that will be used also in [KlokanTech NominatimMatcher JavaScript](https://github.com/klokantech/javascript/blob/master/src/nominatimmatcher.js#L128).

Now it requires object `address` with a lot of information, that are not in input sample data.

**Comment by klokan** [comment]
@petrsloup please let know @MartinMikita while implementing #11 what are your requirements for the JavaScript interface.

**Comment by klokan** [comment]
The idea is to be compatible with Nominatim - on the features which we use and which are available in OSMNames. So the existing JSON gives us the names of attributes, for example.

**Comment by klokan** [comment]
The first version exists now. If there are new changes required - let's create a new ticket for Miki.
