### ISSUE TITLE
UK Postcode search

### ISSUE THREAD

**Issue by klokan** [klokantech/osmnames-sphinxsearch#41]
We should include UK Postcode search data into the index.

Probably easiest is to use the CSV:

CSV ukpostcodes.zip (33MB zipped, 96MB unzipped)
https://www.freemaptools.com/download/full-postcodes/ukpostcodes.zip
Header is in the first row : id,postcode,latitude,longitude

from
https://www.freemaptools.com/download-uk-postcode-lat-lng.htm

Attribution:
Contains Ordnance Survey data © Crown copyright and database right 2016
Contains Royal Mail data © Royal Mail copyright and database right 2016
Contains National Statistics data © Crown copyright and database right 2016

We will write a script and publish it here which process the data into correct form.

The data is derived from:
https://www.ordnancesurvey.co.uk/business-and-government/products/code-point-open.html
and one more open data dataset.

**Comment by mtmail** [comment]
Ordnancesurvey (ONS) code point open doesn't include Northern Ireland so double-check the licensing of the Northern Ireland postcodes in the freemaptools' dataset.

https://www.ons.gov.uk/methodology/geography/licences "If you also use the Northern Ireland data (postcodes starting with “BT”), you need a separate licence for commercial use direct from Land and Property Services." "Use of the Northern Ireland data contained within the ONS postcode products constitutes acceptance of the Northern Ireland licensing terms and conditions."

**Comment by klokan** [comment]
Let's filter the Ireland out temporary - because of the license issues.

**Comment by MartinMikita** [comment]
[The shell script](https://gist.github.com/MartinMikita/5facdf2a9c6b00c3ba9a36db6cf48e2b) for downloading and filtering out Northern Ireland post codes.

Processing script which outputs TSV file format with required fields for correct OSMNames search utility is included in [the configuration of SphinxSearch](https://github.com/klokantech/osmnames-sphinxsearch/blob/master/conf/sphinx/sphinx.conf#L310).

The SphinxSearch configuration is prepared to process any postcodes using the same format of CSV.
The files should be named `postcodes-<country_code>.csv`. Now only `postcodes-uk.csv` is recognized and processed, but it can be any other country as well.


Short overview:
 - expected fields of input CSV file for postcodes: `id`, `postcode`, `lat`, `lon`
 - Config script generates `name`, `display_name` attributes same as `postcode`
 - Config script generates `importance` with "1.0" value and `type` with "postcode" value (static data)
 - Config script makes point bounding box attributes `west`, `south`, `east`, `north` from `lon`, `lat`
 - Web server parse expected UK PostCode and using fulltext search to find something, which should be in the top of the results now (while importance is higher than any OSM data)
