### ISSUE TITLE
Invalid input data

### ISSUE THREAD

**Issue by MartinMikita** [klokantech/osmnames-sphinxsearch#5]
File `roads.tsv` is invalid.

Line 2865 cannot be processed

```
    service service -65.75578753007225  -28.591789073956882 -65.7567988066901   -28.59293345519714  -65.75498622012884  -28.591789073956882
    parking_aisle   -65.75578753007225  -28.591789073956882 -65.7567988066901   -28.59293345519714  -65.75498622012884  -28.591789073956882
```

Last line is missing one column.
empty values needs to be separated by \t!
First column is empty - name, following \t, following "parking_aisle", following \t, and then there is number, while it should be string value for `type` (if "parking_aisle" is `class`)

**Comment by klokan** [comment]
Please ignore wrong lines - so that we have the first version online. We will fix it in next exports.

**Comment by MartinMikita** [comment]
This line 3 959 903: 

```
num "Calle Hurácan Calle Hurácan" street  residential -117.11162805938092 32.51485109679982   -117.11162805938092 32.51483894304023   -117.11076028094536 32.51485109679982
```

Contains character `\r` in name, after first `Calle Hurácan`
cat/awk this line shows as:

```
Calle Hurácan" street  residential -117.11162805938092 32.51485109679982   -117.11162805938092 32.51483894304023   -117.11076028094536 32.51485109679982
```

In this case, first column (added by awk script) is missing.

**Comment by MartinMikita** [comment]
Fixed by command `cat /data/input/data.tsv | sed -e 's/\r/ /g'`
