### ISSUE TITLE
Looking for "Bruselas" in Osmnames-sphinxsearch

### ISSUE THREAD

**Issue by SantiagoHorcajo** [klokantech/osmnames-sphinxsearch#50]
Hi.
We're testing osmnames-sphinxsearch docker latest version (> 2.0.1, maybe 2.0.2?) with osmnames data version 2.0.2.
We've searched "Bruselas" (spanish alias of Brussels) and osmnames-sphinxsearch doesn't show the expected result, which is the capital of Belgium as the first result. It shows cities from Colombia and so on.
We've reviewed data in planet-latest_geonames.tsv.gz (cat planet-latest_geonames.tsv | grep Bruselas) and Brussels appears with the highest importance and the lowest place_rank. Besides, Bruselas is included in alternative_names field.
Why osnames-sphinxsearch doesn't show it?
Best regards,
Santiago

**Comment by MartinMikita** [comment]
Hello Santiago,

The main problem is, that there exist other records with an exact form "Bruselas" in the `name` column, which is now highly promoted in the search engine.
The field `alternative_names` has lower priority when making the search.

If you want to promote names in the Spanish, you will need to generate your own OSMNames dataset, according to the [related ticket](https://github.com/OSMNames/OSMNames/issues/55).

You may as well change the priorities and importance of the fields to search [in the code](https://github.com/klokantech/osmnames-sphinxsearch/blob/master/web/websearch.py#L685) and deploy your own osmnames-sphinxsearch build.
