### ISSUE TITLE
Can't Connect to MySQL Database error

### ISSUE THREAD

**Issue by wcom939** [klokantech/osmnames-sphinxsearch#59]
Hi,

I started the docker with the following command:
 docker run -d --name klokantech-osmnames-sphinxsearch -v /home/user/OSMNames/data/export/:/data/input/ -p 80:80 klokantech/osmnames-sphinxsearch

in the data/export folder was the north american .tsv files.

The docker image states reindexing is already completed:
skipping non-plain index 'ind_names_infix_soundex'...
skipping non-plain index 'ind_name_prefix'...
skipping non-plain index 'ind_names_prefix'...
total 400400 reads, 1.029 sec, 0.5 kb/call avg, 0.0 msec/call avg
total 884 writes, 0.268 sec, 351.3 kb/call avg, 0.3 msec/call avg
WARNING: failed to open pid_file '/tmp/sphinxsearchd.pid'.
WARNING: indices NOT rotated.
Reindex finished: 20180408 151137
sphinx: started
Finished: 20180408 151139

However I see the following error when querying for "New York":
![image](https://user-images.githubusercontent.com/16446451/38469120-d4758f0c-3b1d-11e8-8db5-096c15fbeb4a.png)

**Comment by oas** [comment]
@wcom939 hi, have you ever found a solution to the problem? I'm getting the same messages, even after 24 hours.

**Comment by thandaanda** [comment]
Open docker container's bash
`docker exec -i -t klokantech-osmnames-sphinxsearch bash`

Run this script in the shell
`/usr/bin/indexer -c /etc/sphinxsearch/sphinx.conf --rotate --all`

Once all the indexes are rebuilt, script will rotate indexes and restart the sphinx server.

**Comment by oas** [comment]
@thandaanda It worked, thank you very much!
