### ISSUE TITLE
Deploy OSMNames v0.3

### ISSUE THREAD

**Issue by klokan** [klokantech/osmnames-sphinxsearch#6]
Let's update the project to index sample data prepared by @and01 and released at:
https://github.com/geometalab/OSMNames/releases/tag/v0.3

The new version with sample Swiss data should be then deployed to http://osmnames.klokantech.com/.

**Comment by MartinMikita** [comment]
Deployed on http://osmnames.klokantech.com/

Available filters (in format `?filter=value`):
- class
- type
- streeet
- city
- county
- state
- country_code
- country

Also viewbox filter: `viewbox=south,west,north,east` filtering on `lat`, `lon` inside this bounding box.
