### ISSUE TITLE
load tiles from tileserver instead of mapbox

### ISSUE THREAD

**Issue by MoustafaMahgoub** [klokantech/osmnames-sphinxsearch#60]
I have tile server set up , Can I use the tiles from there instead of loading them online from mapbox !

**Comment by MartinMikita** [comment]
If you are referring to the main home page of this container, you are using the tiles from KlokanTech, not MapBox.

But, you can freely change that to your local resources, if you are able to provide required TileJSONs [in this source](https://github.com/klokantech/osmnames-sphinxsearch/blob/master/web/templates/home.html#L27).

Or you can create and use your own HTML with loading your map tiles, and append the minimum required code for using AutoComplete feature on one HTML input box.
See [more details here](http://osmnames.org/api/#autocomplete-javascript-component).

This issue has no action for this repository, therefore I am closing it.

**Comment by MoustafaMahgoub** [comment]
thank you for your answer @MartinMikita , I am quit newbie 
 
do you know how to add it to the code,I tried but it is not working, I replaced the source but the tiles did not load

  var map = new kt.VectorMap(
        'https://tileserver.espri-geoserver.fokus.fraunhofer.de/styles/klokantech-basic.json?key=tX0QWNRowlarrQpqxngS',


I am serving Dach tiles on Debian server. 
I added this line (this is the server which i am serving the tiles from ).
