### ISSUE TITLE
Using your own data

### ISSUE THREAD

**Issue by MoustafaMahgoub** [klokantech/osmnames-sphinxsearch#61]
I am typing this command to work with docker file but it returns the sample data everytime ; my docker command is 
docker run -d --name klokantech-osmnames-sphinxsearch -v /Users/mma/Desktop/osmnames-sphinxsearch-master/data/index:/data/index/  -v /Users/mma/Desktop/osmnames-sphinxsearch-master/data/input/:/data/input/data.tsv -p 80:80  klokantech/osmnames-sphinxsearch

I am using the data from export of osmnames, and i made directory data/input/data.tsv

**Comment by MartinMikita** [comment]
Dear Moustafa,

Please, read carefully our [README](https://github.com/klokantech/osmnames-sphinxsearch#usage-of-docker-image) about using docker image.

You have a wrong command for linking input data.tsv.
It should be **`-v /Users/mma/Desktop/osmnames-sphinxsearch-master/data/input/:/data/input/`**.
