### ISSUE TITLE
Filter result by class.

### ISSUE THREAD

**Issue by vitas13** [klokantech/osmnames-sphinxsearch#62]
Hallo,
Can i run a query like this /gb/q/Lon.js, and filter it by specific class eg:
/gb/q/Lon.js&/r/boundary,place.js?key=xyz
Lukas

**Comment by MartinMikita** [comment]
Hi,

You can filter query on the main search route now, see [the code](https://github.com/klokantech/osmnames-sphinxsearch/blob/master/web/websearch.py#L928).
It could look like this:
`/?q=Lon&class=boundary,place&country_code=gb`

This filter is not implemented for the routes `/q/Lon.js` now.

Note also that, these URLs are not permitted in [MapTiler Cloud Geocoding service](https://cloud.maptiler.com/geocoding/) now.
