### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MoustafaMahgoub** [klokantech/osmnames-sphinxsearch#63]
Hello, a question here not an issue, 
I am trying to use my server served tiles instead of klokantech , I have changed this part in the code 
"var map = new kt.VectorMap(
        'https://tileserver.espri-geoserver.fokus.fraunhofer.de/styles/klokantech-basic.json'," but the tiles are not loaded.
are there any recommendations you can recommend me to make them work

**Comment by MartinMikita** [comment]
Hi Moustafa,

The first argument of `kt.VectorMap` should be URL to GL Style, not TileJSON link, as you provided.
GL Style URL: https://tileserver.espri-geoserver.fokus.fraunhofer.de/styles/klokantech-basic/style.json

```
var map = new kt.VectorMap(
        'https://tileserver.espri-geoserver.fokus.fraunhofer.de/styles/klokantech-basic/style.json',
        'https://tileserver.espri-geoserver.fokus.fraunhofer.de/styles/klokantech-basic.json',
        'map-ol', 'map-gl').getMap();
```
